INSERT INTO TODO (COMPLETED, TITLE) VALUES (FALSE, 'Buy milk');
INSERT INTO TODO (COMPLETED, TITLE) VALUES (FALSE, 'Buy eggs');
INSERT INTO TODO (COMPLETED, TITLE) VALUES (FALSE, 'Buy bread');
INSERT INTO TODO (COMPLETED, TITLE) VALUES (FALSE, 'Buy cheese');